title: Samylots' github pages lab
author: Samylots
email: samuel.beaudoin.5@ulaval.ca
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome description!

# social links
twitter_username: Samylots
github_username:  Samylots

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-midnight
